"""add updated_at to quotations

Revision ID: 209978e8bd82
Revises: d80f8edb32cd
Create Date: 2026-07-26 23:40:48.609915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209978e8bd82'
down_revision: Union[str, Sequence[str], None] = 'd80f8edb32cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False)
    op.drop_column('quotations', 'updated_at')
    # ### end Alembic commands ###
