"""add n8n resume url to rfqs

Revision ID: 3e879f3a2709
Revises: ad2208798230
Create Date: 2026-08-10 07:30:49.199634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e879f3a2709'
down_revision: Union[str, Sequence[str], None] = 'ad2208798230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('n8n_resume_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'n8n_resume_url')
    # ### end Alembic commands ###
