"""create approvals table

Revision ID: 4626ebaf6f16
Revises: c7b3e042b8eb
Create Date: 2026-07-27 22:13:42.002856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4626ebaf6f16'
down_revision: Union[str, Sequence[str], None] = 'c7b3e042b8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False)
    op.drop_table('approvals')
    # ### end Alembic commands ###
