"""create draft emails table

Revision ID: 574c659a633f
Revises: 4626ebaf6f16
Create Date: 2026-07-27 22:58:52.723979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574c659a633f'
down_revision: Union[str, Sequence[str], None] = '4626ebaf6f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_emails_id'), 'draft_emails', ['id'], unique=False)
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_draft_emails_id'), table_name='draft_emails')
    op.drop_table('draft_emails')
    # ### end Alembic commands ###
