"""replace llm price review with market benchmark

Revision ID: 82895dbdf006
Revises: 3e879f3a2709
Create Date: 2026-08-28 22:57:55.750636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82895dbdf006'
down_revision: Union[str, Sequence[str], None] = '3e879f3a2709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("DELETE FROM price_reviews")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_reviews', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('price_reviews', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('price_reviews', sa.Column('benchmark_low', sa.Float(), nullable=True))
    op.add_column('price_reviews', sa.Column('benchmark_high', sa.Float(), nullable=True))
    op.add_column('price_reviews', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.drop_column('price_reviews', 'summary')
    op.drop_column('price_reviews', 'recommendation')
    op.drop_column('price_reviews', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_reviews', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('price_reviews', sa.Column('recommendation', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('price_reviews', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('price_reviews', 'source_type')
    op.drop_column('price_reviews', 'benchmark_high')
    op.drop_column('price_reviews', 'benchmark_low')
    op.drop_column('price_reviews', 'price')
    op.drop_column('price_reviews', 'status')
    # ### end Alembic commands ###
