"""add missing rfq extraction fields

Revision ID: 917f7d9c7996
Revises: a573b2e44dd3
Create Date: 2026-08-30 20:57:36.773963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917f7d9c7996'
down_revision: Union[str, Sequence[str], None] = 'a573b2e44dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('rfqs', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('rfqs', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('rfqs', sa.Column('gender', sa.String(length=100), nullable=True))
    op.add_column('rfqs', sa.Column('age', sa.String(length=100), nullable=True))
    op.add_column('rfqs', sa.Column('quota', sa.Text(), nullable=True))
    op.add_column('rfqs', sa.Column('project_scope', sa.String(length=100), nullable=True))
    op.add_column('rfqs', sa.Column('end_client', sa.String(length=255), nullable=True))
    op.add_column('rfqs', sa.Column('additional_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'additional_notes')
    op.drop_column('rfqs', 'end_client')
    op.drop_column('rfqs', 'project_scope')
    op.drop_column('rfqs', 'quota')
    op.drop_column('rfqs', 'age')
    op.drop_column('rfqs', 'gender')
    op.drop_column('rfqs', 'target_audience')
    op.drop_column('rfqs', 'city')
    op.drop_column('rfqs', 'region')
    # ### end Alembic commands ###
