"""add gmail thread id and waiting status

Revision ID: a573b2e44dd3
Revises: 82895dbdf006
Create Date: 2026-08-30 13:18:16.096692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a573b2e44dd3'
down_revision: Union[str, Sequence[str], None] = '82895dbdf006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('rfqs', sa.Column('gmail_thread_id', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'gmail_thread_id')
    # ### end Alembic commands ###
