"""initial_schema

Revision ID: ad2208798230
Revises: 
Create Date: 2026-08-05 00:27:01.653137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2208798230'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_email', sa.Text(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('loi', sa.Float(), nullable=True),
    sa.Column('ir', sa.Float(), nullable=True),
    sa.Column('methodology', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('programming_required', sa.Boolean(), nullable=False),
    sa.Column('translation_required', sa.Boolean(), nullable=False),
    sa.Column('overlay_required', sa.Boolean(), nullable=False),
    sa.Column('rush', sa.Boolean(), nullable=False),
    sa.Column('client_tier', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('clarification_questions', sa.JSON(), nullable=False),
    sa.Column('ready_for_quotation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('sample_cost', sa.Float(), nullable=False),
    sa.Column('programming_fee', sa.Float(), nullable=False),
    sa.Column('translation_fee', sa.Float(), nullable=False),
    sa.Column('pm_fee', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('rush_fee', sa.Float(), nullable=False),
    sa.Column('client_discount', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_reviews_id'), 'price_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_price_reviews_quotation_id'), 'price_reviews', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_price_reviews_rfq_id'), 'price_reviews', ['rfq_id'], unique=False)
    op.create_table('draft_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_emails_id'), 'draft_emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_emails_id'), table_name='draft_emails')
    op.drop_table('draft_emails')
    op.drop_index(op.f('ix_price_reviews_rfq_id'), table_name='price_reviews')
    op.drop_index(op.f('ix_price_reviews_quotation_id'), table_name='price_reviews')
    op.drop_index(op.f('ix_price_reviews_id'), table_name='price_reviews')
    op.drop_table('price_reviews')
    op.drop_table('approvals')
    op.drop_table('quotations')
    op.drop_table('rfqs')
    # ### end Alembic commands ###
