"""add gmail message id to rfqs

Revision ID: c1ff1ee874bb
Revises: 917f7d9c7996
Create Date: 2026-08-31 13:40:24.734243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ff1ee874bb'
down_revision: Union[str, Sequence[str], None] = '917f7d9c7996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('gmail_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'gmail_message_id')
    # ### end Alembic commands ###
