"""create quotations table

Revision ID: d80f8edb32cd
Revises: 14bc40212a52
Create Date: 2026-07-26 23:00:31.388751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80f8edb32cd'
down_revision: Union[str, Sequence[str], None] = '14bc40212a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('sample_cost', sa.Float(), nullable=False),
    sa.Column('programming_fee', sa.Float(), nullable=False),
    sa.Column('translation_fee', sa.Float(), nullable=False),
    sa.Column('pm_fee', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('rush_fee', sa.Float(), nullable=False),
    sa.Column('client_discount', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            existing_nullable=False)
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('quotations')
    # ### end Alembic commands ###
