"""add client_email to rfqs

Revision ID: 7ccaa0ce5c83
Revises: 574c659a633f
Create Date: 2026-07-28 23:16:31.029979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccaa0ce5c83'
down_revision: Union[str, Sequence[str], None] = '574c659a633f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('client_email', sa.String(length=255), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'client_email')
    # ### end Alembic commands ###
