"""add price_reviews table

Revision ID: c7b3e042b8eb
Revises: 209978e8bd82
Create Date: 2026-07-27 21:19:18.533316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b3e042b8eb'
down_revision: Union[str, Sequence[str], None] = '209978e8bd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_reviews_id'), 'price_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_price_reviews_quotation_id'), 'price_reviews', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_price_reviews_rfq_id'), 'price_reviews', ['rfq_id'], unique=False)
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('rfqs', 'status',
    #            existing_type=sa.Enum('RECEIVED', 'EXTRACTED', 'VALIDATED', 'CLARIFICATION_REQUIRED', 'READY_FOR_QUOTATION', 'QUOTED', 'PRICE_REVIEWED', 'APPROVED', 'REJECTED', 'EMAIL_DRAFTED', 'COMPLETED', name='rfqstatus'),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_price_reviews_rfq_id'), table_name='price_reviews')
    op.drop_index(op.f('ix_price_reviews_quotation_id'), table_name='price_reviews')
    op.drop_index(op.f('ix_price_reviews_id'), table_name='price_reviews')
    op.drop_table('price_reviews')
    # ### end Alembic commands ###
