from enum import Enum


class RFQStatus(str, Enum):
    RECEIVED = "RECEIVED"
    EXTRACTED = "EXTRACTED"
    VALIDATED = "VALIDATED"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    WAITING_FOR_CLIENT = "WAITING_FOR_CLIENT"

    READY_FOR_QUOTATION = "READY_FOR_QUOTATION"
    QUOTED = "QUOTED"
    PRICE_REVIEWED = "PRICE_REVIEWED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EMAIL_DRAFTED = "EMAIL_DRAFTED"
    COMPLETED = "COMPLETED"